### ISSUE TITLE
Tasks to do

### ISSUE THREAD

**Issue by Akilan1999** [HWTechClub/Virus-Scanner#9]
## Tasks to do:
    - Ensure external libraries are added to requirements.txt
    - Change code in folders from scanner to parameters in the function
    - Create CLI (Command Line interface)

**Comment by itsmokha** [comment]
```
> - Ensure external libraries are added to requirements.txt
 - Change code in folders from scanner to parameters in the function
```
Completed. Only CLI left

**Comment by PC-02** [comment]
Cli completed, testing and cleaning up of files required
